/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.soton.git.comp2211g17;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import uk.ac.soton.git.comp2211g17.controller.MainWindowController;
import uk.ac.soton.git.comp2211g17.view.MainWindow;

public class Main extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        MainWindowController controller = new MainWindowController();
        Scene scene = new Scene(new MainWindow(controller));
        stage.setScene(scene);
        stage.setTitle("Ad auction management interface");
        stage.show();
    }
}
